<?php

namespace RefGPC\_controleurs;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-06 at 23:33:39.
 */
class baseControleurTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var baseControleur
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new baseControleur;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RefGPC\_controleurs\baseControleur::loadModel
     * @todo   Implement testLoadModel().
     */
    public function testLoadModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RefGPC\_controleurs\baseControleur::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RefGPC\_controleurs\baseControleur::render
     * @todo   Implement testRender().
     */
    public function testRender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
